### ISSUE TITLE
Programming Language

### ISSUE THREAD

**Issue by officialpiyush** [developer-hole/gamestats.js#1]
# Lets Vote on what language the library should be in!

* Typescript
* JavaScript

**Comment by Anish-Shobith** [comment]
Shouldn't actually matter, we could add typings if written in js.

**Comment by officialpiyush** [comment]
i go with ts

**Comment by officialpiyush** [comment]
ok

**Comment by Anish-Shobith** [comment]
Lets keep JS for now , and lets convert to ts if needed only ! but I feel typings should get our work done.

Closing this issue for now.
